### PR TITLE
Call callback after passed

### PR DESCRIPTION
**Pull request by zbcjackson**
Add a pass event so that when test passed I can be notified

### CODE REVIEW

**Comment by sindresorhus** [comment]
Try listening to the `end` event.

**Comment by zbcjackson** [comment]
`end` even will be always emitted whether success or  not. And I can't get the result in `end` event

**Comment by sindresorhus** [comment]
I don't really see the point. You already get notified when there's an error. If there's not, you can assume it was a success. Per unix convention, silent on success, loud on failure.

**Comment by zbcjackson** [comment]
For example, I want to turn on green light when the tests pass, red light when the tests failed.

**Comment by Jameskmonger** [comment]
@zbcjackson So turn on a red light on the `error` event, and turn on a green light on the `end` event if `error` wasn't emitted.

**Pull request closed without merging**
