### PR TITLE
Updated readme.md, added one more option to mocha

### PR DESCRIPTION
**Pull request by musahaidari**
This explains how to set custom path for the tests directory. I searched online and could not find a useful doc for the same, hope this helps.

### CODE REVIEW

**Comment by sindresorhus** [comment]
What exactly does that option do? Your description is not very clear. Can you link to the Mocha docs about it?

**Comment by musahaidari** [comment]
I meant, using the option `test` in `mocha-gulp()` let's you define a custom path to the tests files, that is by default is `PROJECT_ROOT/test`. Now if you place your tests inside a custom directory, then to run them using mocha in command line you say:

     mocha my/custom/path/to/tests/**/*.js

but if you want to tell gulp mocha the custom path of your test files, you will say:

    gulp.task('backEndSpec', function () {
        return gulp.src([
                'my/custom/path/to/tests/**/*.js'
            ], {read: false})
            .pipe(gulpMocha({
                test: 'my/custom/path/to/tests/**/*.js', // Please pay attention to this line
                reporter: 'spec',
                timeout: 5000
            }))
            .on('error', gulpUtil.log);
    });

Regarding the docs, I could not find it on official docs, it just works! Maybe you can help me figure out how.

**Comment by sindresorhus** [comment]
There's no default path in `gulp-mocha`. It uses the paths you supply it in `gulp.src`. I still don't see what you're trying to achieve with the `test` option. It seems it's just duplicating the `gulp.src` argument.

**Comment by musahaidari** [comment]
Gulp.src are the files to load, and the option that I added sets the files
to be watched. I think it would be a good idea, if you get time, to try to
actually create a demo project and test it with and without 'test' option.

**Comment by sindresorhus** [comment]
> and the option that I added sets the files to be watched

This answers what I've been asking you this whole time.

You should use `gulp.watch` to do file watching.

**Pull request closed without merging**
