### PR TITLE
Add note on termination

### PR DESCRIPTION
**Pull request by morenoh149**
How to kill the test if it does not terminate after finishing.
Closes https://github.com/sindresorhus/gulp-mocha/issues/54

### CODE REVIEW

**Comment by juanpabloaj** [comment]
@morenoh149 but, if I add `process.exit(); ` this kill the  a `gulp.watch` command

**Comment by neoziro** [comment]
@morenoh149 how about the return code?

**Comment by neoziro** [comment]
The good way to do it is:

```js
return gulp.src('test/**/*', {read: false})
  .pipe(mocha())
  .once('error', function () {
    process.exit(1);
  })
  .once('end', function () {
    process.exit();
  });
```

**Comment by morenoh149** [comment]
@neoziro @juanpabloaj submit a pull request :)

**Comment by neoziro** [comment]
@morenoh149 done #77

**Pull request merged**
